// Public API re-exports
pub use cat_animation::CatAnimation;
pub use core::Renderer;
pub use dashboard::MENU_ITEMS;

// Internal modules
pub mod agent_tree;
pub mod ai_chat;
mod ai_chat_bubble;
mod ai_chat_event_rows;
mod ai_chat_header;
mod ai_chat_history;
mod ai_chat_input;
mod ai_chat_layout;
mod ai_chat_pickers;
mod ai_chat_style;
mod ai_chat_text;
mod buffer;
pub mod cat_animation;
pub mod conversation_tree;
mod core;
pub mod dashboard;
mod debug_panels;
mod display_math;
mod file_tree_widget;
mod helpers;
mod layout;
pub mod line_cache;
pub mod lsp_manager;
mod markdown;
mod markdown_conceal;
mod overlays;
mod picker_widget;
mod popup_placement;
mod run_console;
pub mod search_replace;
mod status_widgets;
mod styles;
mod terminal_images;
mod test_panel;
