import type { GuiSnapshot, GuiTheme } from "./types";

const theme: GuiTheme = {
  name: "tokyonight",
  background: "#090b12",
  foreground: "#c8d3f5",
  surface: "#111522",
  surfaceSelected: "#242b45",
  border: "#252b3d",
  accent: "#82aaff",
  accentForeground: "#101018",
  muted: "#59647e",
  cursorLine: "#111827",
  selection: "#31456f",
  search: "#62552b",
  error: "#ff757f",
  warning: "#ffc777",
  info: "#65bcff",
  success: "#c3e88d",
  syntax: {
    keyword: "#c099ff",
    function: "#82aaff",
    type: "#ffc777",
    "type-builtin": "#65bcff",
    string: "#c3e88d",
    number: "#fca7ea",
    comment: "#636da6",
    operator: "#89ddff",
    variable: "#c8d3f5",
    "variable-builtin": "#ff757f",
    macro: "#c099ff",
    constant: "#ff966c",
    property: "#65bcff",
    parameter: "#c8d3f5",
    punctuation: "#7a88cf",
  },
};

const source = [
  [["use ", "keyword"], ["solid_js", "type"], ["::{create_signal, For, Show};", "punctuation"]],
  [],
  [["#[derive(Debug, Clone)]", "macro"]],
  [["pub struct ", "keyword"], ["EditorSurface", "type"], [" {", "punctuation"]],
  [["    revision", "property"], [": ", "punctuation"], ["u64", "type-builtin"], [",", "punctuation"]],
  [["    file_name", "property"], [": ", "punctuation"], ["String", "type"], [",", "punctuation"]],
  [["    mode", "property"], [": ", "punctuation"], ["Mode", "type"], [",", "punctuation"]],
  [["}", "punctuation"]],
  [],
  [["impl ", "keyword"], ["EditorSurface", "type"], [" {", "punctuation"]],
  [["    pub fn ", "keyword"], ["snapshot", "function"], ["(&self) -> ViewModel {", "punctuation"]],
  [["        ViewModel", "type"], [" {", "punctuation"]],
  [["            title", "property"], [": ", "punctuation"], ["self", "variable-builtin"], [".file_name.clone(),", "variable"]],
  [["            status", "property"], [": ", "punctuation"], ["\"ready\"", "string"], [".into(),", "function"]],
  [["        }", "punctuation"]],
  [["    }", "punctuation"]],
  [["}", "punctuation"]],
  [],
  [["// The DOM is a projection; Ovim remains the editor.", "comment"]],
] as const;

export const mockSnapshot: GuiSnapshot = {
  revision: 42,
  mode: "NORMAL",
  dashboard: false,
  filePath: "/workspace/ovim/ovim/src/gui/mod.rs",
  fileName: "mod.rs",
  projectName: "ovim",
  language: "rust",
  encoding: "UTF-8",
  lineEnding: "LF",
  modified: true,
  readOnly: false,
  selectionText: undefined,
  cursor: { line: 12, column: 12, displayColumn: 12 },
  horizontalOffset: 0,
  wrap: false,
  tabWidth: 4,
  firstLine: 0,
  totalLines: 742,
  lines: source.map((line, index) => ({
    number: index + 1,
    continuation: false,
    displayStart: 0,
    current: index === 12,
    git: index === 3 ? "added" : index === 12 ? "modified" : undefined,
    diagnostic: index === 10 ? "warning" : undefined,
    segments: line.length
      ? line.map(([text, token], segment) => ({
          text,
          cells: Array.from(text).length,
          token,
          cursor: index === 12 && segment === 0,
          selected: false,
          searchMatch: false,
        }))
      : [{ text: " ", cells: 1, cursor: false, selected: false, searchMatch: false }],
  })),
  layout: { kind: "pane", pane: 0 },
  panes: [],
  tabs: [
    { index: 0, title: "mod.rs", active: true, modified: true },
    { index: 1, title: "FRONTEND_API.md", active: false, modified: false },
  ],
  activeTab: 0,
  gitBranch: "gui/tauri-entry",
  gitChanges: { added: 86, modified: 12, removed: 3 },
  diagnostics: { errors: 0, warnings: 1, information: 0, hints: 2 },
  lspStatus: "rust-analyzer: Ready",
  statusMessage: "",
  fileTree: {
    root: "ovim",
    selected: 5,
    items: [
      ["ovim", 0, true, true],
      ["gui", 1, true, true],
      ["src", 2, true, true],
      ["App.tsx", 3, false, false],
      ["styles.css", 3, false, false],
      ["mod.rs", 1, false, false],
      ["frontend", 1, true, false],
      ["main.rs", 1, false, false],
    ].map(([name, depth, directory, expanded], index) => ({
      index,
      name: String(name),
      path: `/workspace/ovim/${name}`,
      depth: Number(depth),
      directory: Boolean(directory),
      expanded: Boolean(expanded),
    })),
  },
  aiChat: undefined,
  testPanel: undefined,
  problems: undefined,
  lspManager: undefined,
  debug: undefined,
  theme,
  shouldQuit: false,
};

mockSnapshot.panes = [{
  index: 0,
  focused: true,
  fileName: mockSnapshot.fileName,
  modified: mockSnapshot.modified,
  cursor: mockSnapshot.cursor,
  firstLine: mockSnapshot.firstLine,
  scrollSubrow: 0,
  horizontalOffset: mockSnapshot.horizontalOffset,
  totalLines: mockSnapshot.totalLines,
  lines: mockSnapshot.lines,
}];
